# Generated by Django 6.0.7 on 2026-07-28 14:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "size",
                    models.CharField(
                        choices=[("tiny", "Tiny"), ("small", "Small"), ("medium", "Medium"), ("large", "Large")],
                        max_length=10,
                    ),
                ),
                (
                    "friendliness",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "shedding_amount",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "exercise_needs",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "trainability",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("friendliness__range", (1, 5)),
                            ("shedding_amount__range", (1, 5)),
                            ("exercise_needs__range", (1, 5)),
                            ("trainability__range", (1, 5)),
                        ),
                        name="breed_rating_range",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(35),
                        ]
                    ),
                ),
                ("gender", models.CharField(choices=[("male", "Male"), ("female", "Female")], max_length=10)),
                ("color", models.CharField(max_length=100)),
                ("favorite_food", models.CharField(max_length=100)),
                ("favorite_toy", models.CharField(max_length=100)),
                (
                    "breed",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="dogs", to="dogs.breed"
                    ),
                ),
            ],
        ),
    ]
